# Generated by Django 2.0.3 on 2018-05-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('iddirecciones', models.IntegerField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=45)),
                ('numero', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'direcciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuarios', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
