# Generated by Django 2.0.3 on 2018-06-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelsolar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anho', models.DateField(db_column='Anho')),
                ('horario', models.CharField(db_column='Horario', max_length=32)),
                ('nombre', models.CharField(db_column='Nombre', max_length=64)),
                ('codigo', models.CharField(max_length=10)),
                ('ud', models.CharField(db_column='UD', max_length=10)),
            ],
            options={
                'db_table': 'cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='Nombre', max_length=64)),
                ('sitioweb', models.CharField(blank=True, max_length=45, null=True)),
                ('codigo', models.CharField(db_column='Codigo', max_length=10)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolUsuarioCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'rol_usuario_curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Semestres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_semestre', models.CharField(db_column='Nombre_Semestre', max_length=45)),
            ],
            options={
                'db_table': 'semestres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioTipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'usuario_tipo_usuario',
                'managed': False,
            },
        ),
    ]
